# Generated by Django 5.1 on 2024-08-09 12:12

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='CV',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='PDF_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_info',
            field=wagtail.fields.StreamField([('footer_info', wagtail.blocks.TextBlock(template='blocks/footer_info.html'))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='head_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='head_title',
            field=models.CharField(default='Python Fullstack Web Developer', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='languages_frameworks',
            field=wagtail.fields.StreamField([('languages_frameworks', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(help_text='Unique identifier for the card', required=True)), ('title', wagtail.blocks.CharBlock(help_text='Add your card title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='Add your card text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add an image', required=True)), ('live_url', wagtail.blocks.TextBlock(help_text='Add URL for live demo (optional)', required=False)), ('git_url', wagtail.blocks.TextBlock(help_text='Add URL for GitHub repository', required=True))]))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social',
            field=wagtail.fields.StreamField([('social', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True))]))], null=True),
        ),
    ]
