# Generated by Django 5.1 on 2024-08-15 18:13

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_cv_homepage_pdf_logo_homepage_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_section',
            field=wagtail.fields.StreamField([('image_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
