# Generated by Django 5.1 on 2024-08-18 19:04

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_section',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_block',
            field=wagtail.fields.StreamField([('image_text', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
