# Generated by Django 5.1 on 2024-08-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_about_section_homepage_about_block'),
    ]

    operations = [
    ]
