# Generated by Django 5.1 on 2024-08-18 20:01

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_footer_info_alter_homepage_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='CV',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='PDF_logo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('cv_download_block', wagtail.blocks.StructBlock([('pdf_logo', wagtail.images.blocks.ImageChooserBlock(help_text='Logo to represent the PDF download', required=True)), ('cv_file', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload the CV document', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_block',
            field=wagtail.fields.StreamField([('about_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
