# Generated by Django 5.1 on 2024-08-18 20:22

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_cv_remove_homepage_pdf_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('cv_download_block', wagtail.blocks.StructBlock([('pdf_logo', wagtail.images.blocks.ImageChooserBlock(help_text='Logo to represent the PDF download', required=True)), ('option', wagtail.blocks.ChoiceBlock(choices=[('file', 'File'), ('link', 'Link')], help_text='Choose between uploading a file or using a link')), ('cv_file', wagtail.documents.blocks.DocumentChooserBlock(help_text="Upload the CV document (if 'File' is selected)", required=False)), ('external_link', wagtail.blocks.URLBlock(help_text="External URL for CV (if 'Link' is selected)", required=False))]))], blank=True, null=True),
        ),
    ]
