# Generated by Django 5.1 on 2024-08-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='cv',
        ),
    ]
