# Generated by Django 5.1 on 2024-08-18 20:35

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_body_homepage_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='social',
            field=wagtail.fields.StreamField([('social', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('option', wagtail.blocks.ChoiceBlock(choices=[('url', 'URL'), ('email', 'Email')], help_text='Choose whether this is a URL or an email.')), ('url', wagtail.blocks.URLBlock(help_text="URL of the social profile (if 'URL' is selected).", required=False)), ('email', wagtail.blocks.EmailBlock(help_text="Email address (if 'Email' is selected).", required=False))]))], blank=True, null=True),
        ),
    ]
