# Generated by Django 5.1 on 2024-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head_title_second',
            field=models.CharField(default='Fullstack Web Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='head_title',
            field=models.CharField(default='Jon Bergerøy', max_length=100),
        ),
    ]
