# Generated by Django 5.1 on 2024-10-03 12:02

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_head_title_second_alter_homepage_head_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='head_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='head_title_second',
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_block',
            field=wagtail.fields.StreamField([('header', wagtail.blocks.StructBlock([('head_title', wagtail.blocks.CharBlock(default='Jon Bergerøy', max_length=100, required=True)), ('head_title_second', wagtail.blocks.CharBlock(default='Fullstack Web Developer', max_length=100, required=True)), ('head_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
