# Generated by Django 5.1 on 2024-10-04 08:47

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_homepage_head_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='cv',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social',
            field=wagtail.fields.StreamField([('social', wagtail.blocks.StructBlock([('email', wagtail.blocks.CharBlock(help_text='Your email.', required=True)), ('phone', wagtail.blocks.CharBlock(help_text='Your phone number.', required=True)), ('document_upload', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload your document.', required=True)), ('logo_upload', wagtail.images.blocks.ImageChooserBlock(help_text='Upload your pdf logo.', required=True))]))], blank=True, null=True),
        ),
    ]
