# Generated by Django 5.1 on 2024-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_social'),
    ]

    operations = [
    ]
