# Generated by Django 5.1 on 2024-10-04 09:45

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='social',
            field=wagtail.fields.StreamField([('social_block', wagtail.blocks.StructBlock([('email', wagtail.blocks.CharBlock(help_text='Your email.', required=True)), ('phone', wagtail.blocks.CharBlock(help_text='Your phone number.', required=True)), ('cv_document', wagtail.documents.blocks.DocumentChooserBlock(help_text='Upload your document.', required=True)), ('cv_logo', wagtail.images.blocks.ImageChooserBlock(help_text='Upload your pdf logo.', required=True))]))], blank=True),
        ),
    ]
