# Generated by Django 5.1 on 2024-10-04 11:14

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_homepage_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_block',
            field=wagtail.fields.StreamField([('about_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.ListBlock(wagtail.blocks.TextBlock(required=True), min_num=1))]))], blank=True, null=True),
        ),
    ]
