# Generated by Django 5.1 on 2024-10-04 11:40

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_homepage_about_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='languages_frameworks',
            field=wagtail.fields.StreamField([('languages_frameworks', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=100, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
