# Generated by Django 5.1 on 2024-10-04 12:06

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_homepage_languages_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='languages_frameworks',
            field=wagtail.fields.StreamField([('languages_frameworks', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('description', wagtail.blocks.RichTextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
