# Generated by Django 5.1 on 2024-10-10 19:37

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homepage_languages_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='languages_frameworks',
            field=wagtail.fields.StreamField([('language_framework', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=50, required=True)), ('logo', wagtail.images.blocks.ImageChooserBlock(required=True))]))], blank=True, null=True),
        ),
    ]
